services:
    gemini-juggler:
        build: .
        ports:
            - "57061:57061"
        image: gemini-juggler
        container_name: gemini-juggler
        restart: unless-stopped
        volumes:
            - type: bind
              source: ./config.toml
              target: /config.toml
